local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  resolution: 0.1

  observation_sources: laser_scan_sensor #point_cloud_sensor

  laser_scan_sensor: {sensor_frame: /base_link_laser,
                      data_type: LaserScan,
                      topic: /sensors/scan,
                      marking: true,
                      clearing: true,
                      expected_update_rate: 0.15}

